### ISSUE TITLE
Getting Calling State Error

### ISSUE THREAD

**Issue by MuhammadAliKust** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#28]
The app was working fine, but after 1 month when I try to run app then im getting this weird issue.

```
I/PLogger (26423): {call}  {start call button}  {update call id, call_dWEOFKsbtTe58eeph6ZH11GMTGF2_1701498194286}  {02/12/2023 11:23:14}  {INFO}
[log] dWEOFKsbtTe58eeph6ZH11GMTGF2
I/PLogger (26423): {call}  {start call button}  {start request}  {02/12/2023 11:23:21}  {INFO}
I/flutter (26423): send invitation: invitees:[bFtggzLFPBQHAysEWkz9iFI1Glj1], timeout:60, type:0, zimExtendedData:{"inviter_id":"dWEOFKsbtTe58eeph6ZH11GMTGF2","inviter_name":"Emulator","type":0,"data":"{\"call_id\":\"call_dWEOFKsbtTe58eeph6ZH11GMTGF2_1701498194286\",\"invitees\":[{\"user_id\":\"bFtggzLFPBQHAysEWkz9iFI1Glj1\",\"user_name\":\"Phone\"}],\"timeout\":60,\"custom_data\":\"\"}"}, notification config:title:Emulator, message:Incoming voice call..., resource id:zegouikit_call, voIPConfig:{iOSVoIPHasVideo: false, }, notify:true
I/PLogger (26423): {signaling}  {invitation}  {send invitation, invitees:[bFtggzLFPBQHAysEWkz9iFI1Glj1], timeout:60, extendedData:{"inviter_id":"dWEOFKsbtTe58eeph6ZH11GMTGF2","inviter_name":"Emulator","type":0,"data":"{\"call_id\":\"call_dWEOFKsbtTe58eeph6ZH11GMTGF2_1701498194286\",\"invitees\":[{\"user_id\":\"bFtggzLFPBQHAysEWkz9iFI1Glj1\",\"user_name\":\"Phone\"}],\"timeout\":60,\"custom_data\":\"\"}"}, push config:{title: Emulator, message: Incoming voice call..., payload: {"inviter_id":"dWEOFKsbtTe58eeph6ZH11GMTGF2","inviter_name":"Emulator","type":0,"data":"{\"call_id\":\"call_dWEOFKsbtTe58eeph6ZH11GMTGF2_1701498194286\",\"invitees\":[{\"user_id\":\"bFtggzLFPBQHAysEWkz9iFI1Glj1\",\"user_name\":\"Phone\"}],\"timeout\":60,\"custom_data\":\"\"}"}, resourceID: zegouikit_call, voipConfig:{iOSVoIPHasVideo: false, }}}  {02/12/2023 11:23:21}  {INFO}
I/zego_jni(26423): [2023-12-2 14:23:21:192][Verbose][API] callInvite. handle: 3919183306, invitess count: 1, timeout: 60, extended data: {"inviter_id":"dWEOFKsbtTe58eeph6ZH11GMTGF2","inviter_name":"Emulator","type":0,"data":"{\"call_id\":\"call_dWEOFKsbtTe58eeph6ZH11GMTGF2_1701498194286\",\"invitees\":[{\"user_id\":\"bFtggzLFPBQHAysEWkz9iFI1Glj1\",\"user_name\":\"Phone\"}],\"timeout\":60,\"custom_data\":\"\"}"}, offline push: (title size: 8, content size: 22, extended_data size: 277, resources id:zegouikit_call)
I/zego_jni(26423): [2023-12-2 14:23:21:447][Verbose][Callback] OnCallInvitationSent: call id: 1919339996, code: 0, msg: operation was successful, seq: 2
I/zego_jni(26423): [2023-12-2 14:23:21:452][Verbose][Callback] OnCallUserStateChanged: call id: 1919339996,call user info list:2
I/PLogger (26423): {signaling}  {invitation}  {send invitation, done, invitation id:1919339996, error invitees:()}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {uikit}  {signaling invitation data}  {send invitation done, invitationID:1919339996}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {uikit}  {signaling invitation data}  {add invitation data id:1919339996, type:0, inviter id:dWEOFKsbtTe58eeph6ZH11GMTGF2, invitees:(userid :bFtggzLFPBQHAysEWkz9iFI1Glj1, state:InvitationState.waiting), data:{"call_id":"call_dWEOFKsbtTe58eeph6ZH11GMTGF2_1701498194286","invitees":[{"user_id":"bFtggzLFPBQHAysEWkz9iFI1Glj1","user_name":"Phone"}],"timeout":60,"custom_data":""}, resourceID:zegouikit_call}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {uikit}  {signaling invitation data}  {invite success, invitationID:1919339996}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {call}  {start call button}  {start call button pressed, code:, message:, invitation id:1919339996, error invitees:[]}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {call}  {page manager}  {local send invitation, call id:call_dWEOFKsbtTe58eeph6ZH11GMTGF2_1701498194286, invitees:[{id:bFtggzLFPBQHAysEWkz9iFI1Glj1, name:Phone, in-room attributes:{}, camera:false, microphone:false, microphone mute mode:false }], type: ZegoCallType.voiceCall, code:, message:, error invitees:[], invitation id:1919339996}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {call}  {ringtone}  {start ring, source path:assets/invitation/audio/outgoing.mp3}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {call}  {machine}  {calling, from State[CallingState.kIdle] to State[CallingState.kCallingWithVoice]}  {02/12/2023 11:23:21}  {INFO}
E/flutter (26423): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'TransitionError<CallingState>'
E/flutter (26423): #0      Machine.current= (package:statemachine/src/machine.dart:144:7)
E/flutter (26423): #1      State.enter (package:statemachine/src/state.dart:71:27)
E/flutter (26423): #2      ZegoInvitationPageManager.onLocalSendInvitation (package:zego_uikit_prebuilt_call/src/call_invitation/pages/page_manager.dart:332:49)
E/flutter (26423): #3      _ZegoSendCallInvitationButtonState.onPressed (package:zego_uikit_prebuilt_call/src/call_invitation/components/send_call_invitation_button.dart:327:18)
E/flutter (26423): #4      _ZegoStartInvitationButtonState.onPressed.<anonymous closure> (package:zego_uikit/src/plugins/signaling/invitation/components/start_invitation_button.dart:121:25)
E/flutter (26423): <asynchronous suspension>
E/flutter (26423): #5      _ZegoStartInvitationButtonState.onPressed (package:zego_uikit/src/plugins/signaling/invitation/components/start_invitation_button.dart:109:5)
E/flutter (26423): <asynchronous suspension>
E/flutter (26423): 
I/PLogger (26423): {signaling}  {event center}  {onCallUserStateChanged, callUserList:({userID:bFtggzLFPBQHAysEWkz9iFI1Glj1, state:ZIMCallUserState.inviting, extendedData:}, {userID:dWEOFKsbtTe58eeph6ZH11GMTGF2, state:ZIMCallUserState.accepted, extendedData:}),invitationID:1919339996}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {uikit}  {signaling invitation data}  {onInvitationUserStateChanged, {call user list:[{userID:bFtggzLFPBQHAysEWkz9iFI1Glj1, state:ZegoSignalingPluginInvitationUserState.inviting, extended data:}, {userID:dWEOFKsbtTe58eeph6ZH11GMTGF2, state:ZegoSignalingPluginInvitationUserState.accepted, extended data:}]}}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {call}  {page manager}  {on invitation user state changed, user infos:[{userID:bFtggzLFPBQHAysEWkz9iFI1Glj1, state:ZegoSignalingPluginInvitationUserState.inviting, extended data:}, {userID:dWEOFKsbtTe58eeph6ZH11GMTGF2, state:ZegoSignalingPluginInvitationUserState.accepted, extended data:}]}  {02/12/2023 11:23:21}  {INFO}
V/MediaPlayer(26423): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(26423): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/zego_jni(26423): [2023-12-2 14:23:21:684][Verbose][Callback] OnCallUserStateChanged: call id: 1919339996,call user info list:1
I/PLogger (26423): {signaling}  {event center}  {onCallUserStateChanged, callUserList:({userID:bFtggzLFPBQHAysEWkz9iFI1Glj1, state:ZIMCallUserState.received, extendedData:}),invitationID:1919339996}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {uikit}  {signaling invitation data}  {onInvitationUserStateChanged, {call user list:[{userID:bFtggzLFPBQHAysEWkz9iFI1Glj1, state:ZegoSignalingPluginInvitationUserState.received, extended data:}]}}  {02/12/2023 11:23:21}  {INFO}
I/PLogger (26423): {call}  {page manager}  {on invitation user state changed, user infos:[{userID:bFtggzLFPBQHAysEWkz9iFI1Glj1, state:ZegoSignalingPluginInvitationUserState.received, extended data:}]}  {02/12/2023 11:23:21}  {INFO}

```

However call ring is working on receiver device but there is no call UI screen. just getting ringtone.

**Comment by yoer** [comment]
have you try update to latest version of all dependencies?

**Comment by MuhammadAliKust** [comment]
Im using followings dependencies:

zego_uikit_signaling_plugin: ^2.6.7
zego_uikit_prebuilt_call: ^3.17.9

**Comment by yoer** [comment]
problem solved, navigationKey not set.
