### ISSUE TITLE
is Not work android 14 and 15 java application 

### ISSUE THREAD

**Issue by AkalankaKaushalya** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#81]
java.lang.UnsatisfiedLinkError: No implementation found for void im.zego.connection.internal.ZegoConnectionJniApi.setLogFile(java.lang.String) (tried Java_im_zego_connection_internal_ZegoConnectionJniApi_setLogFile and Java_im_zego_connection_internal_ZegoConnectionJniApi_setLogFile__Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at im.zego.connection.internal.ZegoConnectionJniApi.setLogFile(Native Method)
                                                                                                    	at im.zego.connection.internal.ZegoConnectionImpl.setLogFile(ZegoConnectionImpl.java:108)
                                                                                                    	at im.zego.connection.ZegoConnection.setLogFile(ZegoConnection.java:41)
                                                                                                    	at im.zego.uikit.libuikitreport.ZegoConnectionManager.init(ZegoConnectionManager.java:38)
                                                                                                    	at im.zego.uikit.libuikitreport.ReportUtil.create(ReportUtil.java:73)
                                                                                                    	at com.zegocloud.uikit.prebuilt.call.core.CallInvitationServiceImpl.init(CallInvitationServiceImpl.java:233)
                                                                                                    	at com.zegocloud.uikit.prebuilt.call.core.CallInvitationServiceImpl.api_init(CallInvitationServiceImpl.java:673)
                                                                                                    	at com.zegocloud.uikit.prebuilt.call.ZegoUIKitPrebuiltCallService.init(ZegoUIKitPrebuiltCallService.java:45)
                                                                                                    	at com.ep.wineyard.activity.MessageActivity.CallConfig(MessageActivity.java:188)
                                                                                                    	at com.ep.wineyard.activity.MessageActivity.onCreate(MessageActivity.java:98)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8595)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
![Screenshot 2024-12-12 185038](https://github.com/user-attachments/assets/90742336-c4b2-49e9-9e12-2d8aca586f04)

**Comment by yoer** [comment]
I can't reproduce this issue on android 14，plz show me your **flutter doctor -v** infos.

**Comment by yoer** [comment]
Can you provide your apk?

**Comment by yoer** [comment]
Are you running it on a real machine or an emulator?

**Comment by yoer** [comment]
try use **zego_uikit: ^2.27.19**
